version: "3.7"
services:

    adminer:
        image: adminer:4.7-fastcgi
        container_name: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: "192.168.3.2"
        ports:
            - "9000"

    mysql:
        image: mysql:5.6
        container_name: mysql
        restart: always
        working_dir: /var/www/html
        volumes:
            - /var/www/html:/var/www/html
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test"
        ports:
            - "3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    nginx:
        image: nginx:1.17
        container_name: nginx
        restart: always
        working_dir: /var/www/html
        volumes:
            - /var/www/html:/var/www/html
            - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8050:80"
        depends_on:
            - php-fpm

    php-fpm:
        build: ./dev
        container_name: php-fpm
        restart: always
        working_dir: /var/www/html
        environment:
            COMPOSER_MEMORY_LIMIT: "-1"
            PHP_IDE_CONFIG: "serverName=CustomerService"
            XDEBUG_CONFIG: "idekey=PHPSTORM"
            NODE_ENV: "development"
        volumes:
            - .:/var/www/html
            - .:/usr/local/etc/php/conf.d/php.ini
        expose:
            - "9000"
        depends_on:
            - mysql
